# Build ROS
ARG ROS_DISTRO=humble
FROM ros:${ROS_DISTRO}-ros-base

ARG ROS_DISTRO  # Need to re-declare here

# Install colcon and msg tools
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    ros-${ROS_DISTRO}-rosidl-default-generators \
    ros-${ROS_DISTRO}-rosidl-default-runtime \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /output

# Set up non-root user account
ARG GID
ARG UID
RUN groupadd docker --non-unique -g $GID
RUN useradd docker --non-unique -m -u $UID -g $GID
RUN chown docker:docker /home/docker
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
ENV HOME="/home/docker"
USER docker

# Run build_ros.sh
COPY build_ros.sh /
CMD ["/build_ros.sh"]
